[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/*"
  to = "/ProfileView"
  status = 200
[[redirects]]
  from = "/*"
  to = "/MovieView"
  status = 200
  [[redirects]]
  from = "/login"
  to = "/MovieView"
  status = 200
  [[redirects]]
  from = "/signup"
  to = "/MovieView"
  status = 200

  [build]
  command = “CI= npm run build”